version: '3.3'
services:
  api:
    container_name: 'api'
    image: cosmtrek/air
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:4.4'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'